# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20181019_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hood_id',
            new_name='post_hood',
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
